version: "3.8"
services:
  api:
    build: ./api/
    image: api-image:0.1
    container_name: api-container
    ports:
      - '8000:3000'
    volumes:
      - ./api:/app
      - api-volume:/app/node_modules
  frontend:
    build: ./frontend/
    image: frontend-image:0.1
    container_name: frontend-container
    ports:
      - '3000:5173'
    volumes:
      - ./frontend:/app
      - frontend-volume:/app/node_modules
    stdin_open: true
    tty: true
volumes:
  api-volume:
  frontend-volume:

